
all: main.c

clean: 
	rm -rf *.o $(PRG).elf *.bin *.hex *.srec *.bak  
	rm -rf $(PRG)_eeprom.bin $(PRG)_eeprom.hex $(PRG)_eeprom.srec
	rm -rf *.lst *.map 

program: main.hex
	sudo avrdude -F -c usbasp -p m128 -e -U flash:w:$(PRG).hex  -v
