#!/bin/bash
###########################
#Assignment: 4
#Course: CS 344
#Executable: otp_enc_d, otp_dec_d, otp_enc, otp_dec, keygen
#File Name: compileall
#Purpose: build utility
#Author: Spencer Kresge
#Due: 8/15/2015
############################
gcc -o otp_enc_d otp_enc_d.c
gcc -o otp_dec_d otp_dec_d.c
gcc -o otp_enc otp_enc.c
gcc -o otp_dec otp_dec.c
gcc -o keygen keygen.c
